### ISSUE TITLE
Diary 기능 구현

### ISSUE THREAD

**Issue by JaeGeon-SMU** [2023-Capstone/capstone-back#19]
## 구현할 기능 목록

- [x] Diary block 부분 저장
- [ ] 에러 코드 추가

**Comment by jyzayu** [comment]
diary는 block부분만 하면 돼서 block 추가 하시면 됩니다

**Comment by JaeGeon-SMU** [comment]
너무 코드를 많이 작성해 놔서 뭐가 뭔지 한눈에 보기 힘드네요

**Comment by jyzayu** [comment]
짧게 하도록 해볼게요

**Comment by jyzayu** [comment]
com.amazonaws.util.EC2MetadataUtils      : Unable to retrieve the requested metadata (/latest/meta-data/instance-id). Failed to connect to service endpoint: 

com.amazonaws.SdkClientException: Failed to connect to service endpoint:

**Comment by jyzayu** [comment]
그리고 application-local.yml에  datasource.url 이랑 password가 자꾸 바뀌어서 gitignore에 추가하는게 어떠신가요?
 수정할 일 생기면 추가로 말하기로 해요

**Comment by jyzayu** [comment]
merge 완료했습니다.
